language: php

services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - mysql -e 'CREATE DATABASE swidau_test;' -uroot
  - composer install
  - cp config.example.php tests/config.php
  - sed -i "s/database_name_here/swidau_test/" tests/config.php
  - sed -i "s/database_user_here/root/" tests/config.php
  - sed -i "s/database_password_here//" tests/config.php

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs --standard=$TRAVIS_BUILD_DIR/phpcs.xml
