language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - mysql -e 'CREATE DATABASE swidau_test;' -uroot
  - composer install
  - cp config.example.php config.php
  - sed -i "s/database_name_here/swidau_test/" config.php
  - sed -i "s/database_user_here/root/" config.php
  - sed -i "s/database_password_here//" config.php
  - cat config.php

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs --standard=$TRAVIS_BUILD_DIR/phpcs.xml
